apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garbanzo-ingress
  labels:
    app: garbanzo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: garbanzo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: garbanzo-service
            port:
              number: 80